#!/bin/sh
/bin/busybox --install -s

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

echo "Welcome to KoreOS!"

while true; do
    echo "Starting Emergency shell..."
    (
      HOME=/root
      USER=Kore
      LOGNAME=Kore
      SHELL=/bin/sh
      ENV="/root/.profile"

      RED=$(printf '\033[1;31m')
      RESET=$(printf '\033[0m')

      PS1="[${RED}Kore${RESET}@${RED}KoreIso${RESET}:\w] # "

      export HOME USER LOGNAME SHELL ENV PS1

      cd "$HOME"

      clear

      if [ -x /usr/bin/fastfetch ]; then
        /usr/bin/fastfetch
      fi

      /bin/busybox openvt -c 1 -w -- /bin/sh
    )

    echo "Exited Shell."

    if [ -f /tmp/shutdown ]; then
      echo "Shutting down KoreOS..."
      rm -f /tmp/shutdown
      umount /proc /sys /dev 2>/dev/null

      /bin/busybox poweroff -f
    fi

    sleep 1
done
