#!/bin/sh
/bin/busybox --install -s

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

echo "Welcome to KoreOS!"

while true; do
    echo "Starting Emergency shell..."
    (
      HOME=/root
      SHELL=/bin/sh
      ENV="/root/.profile"

      RED=$(printf '\033[1;31m')
      RESET=$(printf '\033[0m')

      PS1="[${RED}root${RESET}@${RED}KoreIso${RESET}:\w] # "

      export HOME SHELL ENV PS1

      cd "$HOME"

      clear

      if [ -x /usr/bin/fastfetch ]; then
        /usr/bin/fastfetch
      fi

      /bin/busybox openvt -c 1 -w -- /bin/sh
    )

    echo "Exited Shell."
    echo "Do you wanna turn off the System? [poweroff/REBOOT]"
    printf "KoreOS:Power> "
    read -r choice

    if [ "$choice" = "poweroff" ]; then
      echo "Powering KoreOS off... "
      umount /proc /sys /dev 2>/dev/null
      /bin/busybox poweroff -d 0 -f
    fi

    sleep 1
done
