#!/bin/sh
/bin/busybox --install -s

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

echo "Welcome to KoreOS!"

while true; do
    echo "Starting Emergency shell..."
    (
      HOME=/root
      PS1="KoreOS:\w# "
      export HOME PS1

      cd "$HOME"

      clear

      if [ -x /usr/bin/fastfetch ]; then
        /usr/bin/fastfetch
      fi

      /bin/sh
    )

    echo "Exited Shell."
    echo "Do you wanna turn off the System? [poweroff/REBOOT]"
    printf "KoreOS:Power> "
    read -r choice

    if [ "$choice" = "poweroff" ]; then
      echo "Powering KoreOS off... "
      umount /proc /sys /dev 2>/dev/null
      /bin/busybox poweroff -d 0 -f
    fi

    sleep 1
done
